### class distribution - handling unbalanced data distribution

handling imbalanced data , when we do classification , we need variety of data , but we observe a majority of data available in one specific area causing imbalance in training , we have to correct this , for this we do undersampling

checking fraudulent and legitimate transactions in credit card transactions

In [1]:
import numpy as np
import pandas as pd

In [ ]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/credit_data.csv"
credit_card_data = pd.read_csv(path)
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [ ]:
credit_card_data.isnull().sum()  #to check missing values

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
#distribution of transaction
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
type(credit_card_data)

pandas.DataFrame

In [10]:
#seperating legit and fraudulent transaction

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
legit.shape

(284315, 31)

In [15]:
fraud.shape

(492, 31)

undersampling , building a sampple dataset containing distribution of legit and fraudulent transaction

no of fraudulent transaction = 492

In [ ]:
legit_sample = legit.sample(n = 492) #we reduced the no of samples of legitimate

In [17]:
legit_sample.shape

(492, 31)

In [18]:
type(legit_sample)

pandas.DataFrame

In [19]:
#concatinate the 2 dataframes

new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
98197,66561.0,-0.921710,0.604315,0.009373,-0.519536,-0.269553,-0.244570,0.916772,0.510744,-0.263596,...,0.146635,0.139840,0.203354,-0.383397,-0.294390,0.322551,0.160773,0.159756,150.91,0
246029,153007.0,2.261121,-1.396813,-0.791662,-1.654752,-1.237526,-0.412513,-1.220675,-0.116354,-1.425062,...,-0.122334,0.170726,0.182608,-0.408417,-0.210626,-0.175863,0.020431,-0.058417,19.60,0
105962,69763.0,1.525601,-0.955909,0.340604,-1.528578,-1.305844,-0.510693,-1.030011,-0.084066,-2.097556,...,-0.191348,-0.156839,-0.008252,-0.010404,0.410526,-0.202515,0.028846,0.005479,0.52,0
58033,48199.0,-0.984664,0.023680,2.573997,-0.538864,0.176094,0.662464,-0.411101,0.394931,0.709890,...,0.137402,0.475707,-0.470413,-0.928575,0.517838,0.642253,0.036616,0.065192,14.95,0
53109,45816.0,-0.290342,0.320609,1.076741,0.221297,0.213658,1.976269,-0.188796,0.608304,0.069072,...,0.454184,1.632324,0.242807,-0.925902,-1.507676,0.558747,0.032118,0.123142,43.00,0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [22]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64