In [15]:
import numpy as np
import pandas as pd

In [16]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv"
customer_data_raw = pd.read_csv(path)
customer_data_raw.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [17]:
customer_data_raw.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [18]:
customer_data_raw.isnull().sum()  #to check missing values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
customer_data_raw.shape

(7043, 21)

In [20]:
customer_data_raw['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [27]:
customer_who_stayed = customer_data_raw[customer_data_raw.Churn == "No"]
customer_who_left = customer_data_raw[customer_data_raw.Churn == "Yes"]

In [28]:
customer_who_stayed.shape

(5174, 21)

In [29]:
customer_who_left.shape

(1869, 21)

In [30]:
customer_who_stayed.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [31]:
customer_who_left.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes

undersampling , building a sampple dataset containing distribution of customer who left and customer who stayed

no of customer who left = 1869

In [ ]:
customer_who_stayed_reduced = customer_who_stayed.sample(n = 1869) #reduced the sample of people who stayed to match the count who left

In [34]:
customer_who_stayed_reduced.shape

(1869, 21)

In [35]:
new_data_set = pd.concat([customer_who_stayed_reduced,customer_who_left],axis = 0)

In [38]:
new_data_set['Churn'].value_counts()

Churn
No     1869
Yes    1869
Name: count, dtype: int64

In [39]:
new_data_set.head(40)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4429,3486-HOOGQ,Female,0,Yes,Yes,70,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Bank transfer (automatic),79.70,5743.3,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
2025,1488-PBLJN,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),116.85,8477.7,No
3483,4465-VDKIQ,Female,0,No,No,18,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,77.80,1358.6,No
3416,0603-OLQDC,Male,0,No,Yes,12,Yes,No,DSL,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,69.85,837.5,No
6335,7798-JVXYM,Female,0,No,No,14,Yes,No,DSL,No,...,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,69.65,921.4,No
1193,5232-NXPAY,Female,0,No,No,47,Yes,No,DSL,No,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,74.45,3510.3,No
6366,2845-KDHVX,Female,0,Yes,No,64,Yes,No,DSL,No,...,Yes,Yes,No,Yes,Two year,Yes,Mailed check,68.30,4378.8,No
1835,8356-WUAOJ,Female,0,Yes,No,1,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,45.00,45,No
3363,3474-BAFSJ,Male,0,Yes,No,57,No,No phone service,DSL,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),57.50,3265.95,No
3164,2603-HVKCG,Male,0,No,No,31,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,101.40,3143.65,No
3110,6569-KTMDU,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.10,19.1,No
3235,4825-XJGDM,Female,0,No,No,61,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Credit card (automatic),43.70,2696.55,No
6917,2904-GGUAZ,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,No,No,No,No,Two year,Yes,Bank transfer (automatic),84.05,6052.25,No
5319,9866-OCCKE,Female,1,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,109.75,8075.35,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
3572,1730-ZMAME,Female,1,No,No,32,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,79.50,2665,No
6706,7878-RTCZG,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.90,19.9,No
4662,4018-KJYUY,Male,0,No,Yes,22,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),20.15,432.5,No
2106,4547-FZJWE,Male,0,Yes,Yes,55,Yes,No,DSL,Yes,...,No,No,No,Yes,One year,No,Credit card (automatic),59.45,3157,No
5135,1156-ZFYDO,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Electronic check,19.75,19.75,No
4561,9415-TPKRV,Female,0,Yes,Yes,8,Yes,Yes,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,55.75,446.8,No
30,3841-NFECX,Female,1,Yes,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,No,No,Two year,Yes,Credit card (automatic),96.35,6766.95,No
1276,7005-CYUIL,Female,1,Yes,No,71,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Electronic check,99.40,7168.25,No
5830,6754-WKSHP,Male,0,No,Yes,30,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),25.35,723.3,No
500,4374-YMUSQ,Male,0,No,No,34,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),116.25,3899.05,No
2606,1550-EENBN,Female,0,No,No,31,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,No,Electronic check,104.35,3205.6,No
3409,4806-DXQCE,Female,1,Yes,No,70,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,113.65,7714.65,No
6288,3422-GALYP,Male,0,No,No,2,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,79.45,145.15,No
4744,6139-ZZRBQ,Male,1,No,No,64,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),20.05,1198.05,No
4309,2582-FFFZR,Female,0,No,No,22,No,No phone service,DSL,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,50.60,1073.3,No
5386,6143-JQKEA,Male,0,No,No,10,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),45.80,436.2,No
2357,9251-WNSOD,Female,0,Yes,No,67,Yes,Yes,DSL,Yes,...,Yes,No,No,Yes,One year,No,Mailed check,75.10,5064.45,No
5532,8174-LNWMW,Female,0,No,No,31,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),20.90,689.35,No
6418,2486-WYVVE,Male,0,Yes,No,31,Yes,Yes,DSL,No,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,79.30,2484,No
7028,9281-CEDRU,Female,0,Yes,No,68,Yes,No,DSL,No,...,No,Yes,Yes,No,Two year,No,Bank transfer (automatic),64.10,4326.25,No
4235,7629-WFGLW,Female,1,Yes,No,56,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,No,No,One year,No,Electronic check,95.65,5471.75,No
3033,5795-KTGUD,Female,0,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),110.80,7553.6,No
6880,6976-BWGLQ,Female,0,Yes,Yes,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),25.20,1787.35,No
2771,6366-XIVKZ,Female,0,Yes,Yes,13,Yes,No,DSL,Yes,...,Yes,No,No,Yes,Month-to-month,Yes,Mailed check,63.15,816.8,No