In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/auto-mpg-engine-car.csv"
read_engine_mileage = pd.read_csv(path)
read_engine_mileage.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite

In [ ]:
read_engine_mileage.isnull().sum() #check for missing values

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [4]:
duplicated = read_engine_mileage[read_engine_mileage.duplicated()]
print(duplicated)

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin, car name]
Index: []

In [5]:
read_engine_mileage.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 28.1 KB

In [6]:
read_engine_mileage.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight            int64
acceleration    float64
model year        int64
origin            int64
car name            str
dtype: object

In [ ]:
read_engine_mileage['horsepower'].unique()  #we noticed ? that is junk

<StringArray>
['130', '165', '150', '140', '198', '220', '215', '225', '190', '170', '160',
  '95',  '97',  '85',  '88',  '46',  '87',  '90', '113', '200', '210', '193',
   '?', '100', '105', '175', '153', '180', '110',  '72',  '86',  '70',  '76',
  '65',  '69',  '60',  '80',  '54', '208', '155', '112',  '92', '145', '137',
 '158', '167',  '94', '107', '230',  '49',  '75',  '91', '122',  '67',  '83',
  '78',  '52',  '61',  '93', '148', '129',  '96',  '71',  '98', '115',  '53',
  '81',  '79', '120', '152', '102', '108',  '68',  '58', '149',  '89',  '63',
  '48',  '66', '139', '103', '125', '133', '138', '135', '142',  '77',  '62',
 '132',  '84',  '64',  '74', '116',  '82']
Length: 94, dtype: str

In [ ]:
vc = read_engine_mileage['horsepower'].value_counts() #gets value count for every instance

for value, count in vc.items():   
    print(f"{value}: {count}")

150: 22
90: 20
88: 19
110: 18
100: 17
95: 14
75: 14
105: 12
70: 12
67: 12
65: 10
97: 9
85: 9
140: 7
80: 7
145: 7
?: 6
72: 6
92: 6
78: 6
68: 6
84: 6
130: 5
170: 5
175: 5
180: 5
86: 5
60: 5
71: 5
115: 5
165: 4
76: 4
83: 4
52: 4
120: 4
215: 3
225: 3
190: 3
69: 3
112: 3
96: 3
63: 3
48: 3
125: 3
74: 3
198: 2
160: 2
46: 2
87: 2
153: 2
155: 2
129: 2
98: 2
53: 2
81: 2
79: 2
58: 2
139: 2
62: 2
220: 1
113: 1
200: 1
210: 1
193: 1
54: 1
208: 1
137: 1
158: 1
167: 1
94: 1
107: 1
230: 1
49: 1
91: 1
122: 1
61: 1
93: 1
148: 1
152: 1
102: 1
108: 1
149: 1
89: 1
66: 1
103: 1
133: 1
138: 1
135: 1
142: 1
77: 1
132: 1
64: 1
116: 1
82: 1

In [ ]:
for value in read_engine_mileage['horsepower'].unique():
    try:
        float(value) #tries to convert a string to a float , and if its sucessfull try loop runs or else goes to except 
    except:
        print(value)

?

In [26]:
#handling that anomaly - way 1

# Convert horsepower column to numeric values.
# Invalid entries like "?" are converted to NaN using errors='coerce'.
temp = pd.to_numeric(read_engine_mileage['horsepower'], errors='coerce')

# Display rows where conversion failed (i.e., rows containing invalid/non-numeric values).
read_engine_mileage[temp.isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [28]:
junk = read_engine_mileage

In [36]:
junk.shape

(398, 9)

In [37]:
#drop those rows 
index_to_drop = read_engine_mileage[temp.isnull()].index #index of those junk values
junk.drop(index_to_drop,inplace = True)
junk.shape

(392, 9)

In [ ]:
#method 2.1 - hard coded way (exclude)
without_junk = read_engine_mileage[
    read_engine_mileage['horsepower'] != '?'
]   #either you can exclude and copy

junk2 = read_engine_mileage

#method 2.2 - hard coded way (delete)
indexes_to_drop = read_engine_mileage[
    read_engine_mileage['horsepower'] == '?'
].index

junk2 = read_engine_mileage.drop(indexes_to_drop)

In [ ]:
without_junk.shape

(392, 9)

In [41]:
junk2.shape

(392, 9)